### ISSUE TITLE
视频当中演示的版本已经消失了

### ISSUE THREAD

**Issue by kongkongklng** [qichiyuhub/rule#8]
![1734251261522](https://github.com/user-attachments/assets/7b762c64-18b8-4645-b657-e5a9ca4ee231)

**Comment by fulin6688** [comment]
今天重装了immortalwrt虚拟机，配置文件都备份好了，跟你一样，上去了找，homeproxy已经没了……

**Comment by fulin6688** [comment]
immortalwrt源里面的没CLASH API配置

**Comment by kongkongklng** [comment]
我找了另一个博主的但是和这个博主规则不适配

**Comment by qichiyuhub** [comment]
clash api分支作者停更并且不再构建ipk文件了，可以切换imm官方的但是没有clash api，使用原理差不多 区别就是随着singbox内核版本的升级 随时调整一些参数。个人建议如果想稳定使用singbox还是裸核跑吧，或者使用我仓库的sbshell脚本从debian跑。
