### ISSUE TITLE
singbox模板转换的问题

### ISSUE THREAD

**Issue by amwsuhje** [qichiyuhub/rule#9]
用你的模板转换后，如果没有日本节点，那转换后日本节点"outbounds"部分显示的是"Proxy"，这样子app识别不了，要手动改一下，有没办法解决？
![image](https://github.com/user-attachments/assets/fa02be34-48fd-4cdd-b16f-7998018c0d81)

**Comment by qichiyuhub** [comment]
fork到自己仓库根据自己机场进行修改使用吧。
